apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: lab27
      meta.helm.sh/release-namespace: kasten-io
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
    creationTimestamp: "2026-01-13T11:37:39Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: k10
      app.kubernetes.io/instance: lab27
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k10
      app.kubernetes.io/version: 8.5.0
      component: catalog
      helm.sdk.operatorframework.io/chart: k10
      helm.sh/chart: k10-8.5.0
      heritage: Helm
      release: lab27
    name: catalog-pv-claim
    namespace: kasten-io
    ownerReferences:
    - apiVersion: apik10.kasten.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K10
      name: lab27
      uid: 253f2fce-ceaf-4f67-828b-f6664b9ec0a5
    resourceVersion: "6860647"
    uid: 84783d06-665b-4598-8158-da04b7078407
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: nfs-1
    volumeMode: Filesystem
    volumeName: pvc-84783d06-665b-4598-8158-da04b7078407
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: lab27
      meta.helm.sh/release-namespace: kasten-io
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
    creationTimestamp: "2026-01-13T11:37:39Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: k10
      app.kubernetes.io/instance: lab27
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k10
      app.kubernetes.io/version: 8.5.0
      component: jobs
      helm.sdk.operatorframework.io/chart: k10
      helm.sh/chart: k10-8.5.0
      heritage: Helm
      release: lab27
    name: jobs-pv-claim
    namespace: kasten-io
    ownerReferences:
    - apiVersion: apik10.kasten.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K10
      name: lab27
      uid: 253f2fce-ceaf-4f67-828b-f6664b9ec0a5
    resourceVersion: "6860626"
    uid: 8c1ea903-013d-4e5a-97b0-0ff90461236e
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: nfs-1
    volumeMode: Filesystem
    volumeName: pvc-8c1ea903-013d-4e5a-97b0-0ff90461236e
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: lab27
      meta.helm.sh/release-namespace: kasten-io
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
    creationTimestamp: "2026-01-13T11:37:39Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: k10
      app.kubernetes.io/instance: lab27
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k10
      app.kubernetes.io/version: 8.5.0
      component: logging
      helm.sdk.operatorframework.io/chart: k10
      helm.sh/chart: k10-8.5.0
      heritage: Helm
      release: lab27
    name: logging-pv-claim
    namespace: kasten-io
    ownerReferences:
    - apiVersion: apik10.kasten.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K10
      name: lab27
      uid: 253f2fce-ceaf-4f67-828b-f6664b9ec0a5
    resourceVersion: "6860638"
    uid: e31f2139-77c2-4952-b34a-a952bd0da996
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: nfs-1
    volumeMode: Filesystem
    volumeName: pvc-e31f2139-77c2-4952-b34a-a952bd0da996
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: lab27
      meta.helm.sh/release-namespace: kasten-io
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
    creationTimestamp: "2026-01-13T11:37:39Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: k10
      app.kubernetes.io/instance: lab27
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k10
      app.kubernetes.io/version: 8.5.0
      component: metering
      helm.sdk.operatorframework.io/chart: k10
      helm.sh/chart: k10-8.5.0
      heritage: Helm
      release: lab27
    name: metering-pv-claim
    namespace: kasten-io
    ownerReferences:
    - apiVersion: apik10.kasten.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K10
      name: lab27
      uid: 253f2fce-ceaf-4f67-828b-f6664b9ec0a5
    resourceVersion: "6860650"
    uid: f0281c35-87a5-4a57-83cc-52c1c9deab66
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: nfs-1
    volumeMode: Filesystem
    volumeName: pvc-f0281c35-87a5-4a57-83cc-52c1c9deab66
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: lab27
      meta.helm.sh/release-namespace: kasten-io
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
      volume.kubernetes.io/storage-provisioner: cluster.local/nfs-ocp02-provisioner-1
    creationTimestamp: "2026-01-13T11:37:39Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: prometheus
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: lab27
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus
      app.kubernetes.io/version: v3.4.0
      component: server
      helm.sdk.operatorframework.io/chart: k10
      helm.sh/chart: prometheus-27.16.0
      release: lab27
    name: prometheus-server
    namespace: kasten-io
    ownerReferences:
    - apiVersion: apik10.kasten.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K10
      name: lab27
      uid: 253f2fce-ceaf-4f67-828b-f6664b9ec0a5
    resourceVersion: "6861062"
    uid: 29f9247e-05c9-4651-93b5-48dd5a75821f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-1
    volumeMode: Filesystem
    volumeName: pvc-29f9247e-05c9-4651-93b5-48dd5a75821f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
